name: CI
on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [ published ]

jobs:
  buildtest:
    name: Build-Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
          py-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        id: setup-py
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}
      - name: Poetry
        run: pipx install poetry==1.8.2
      - name: Poetry install
        run: |
          poetry env use '${{ steps.setup-py.outputs.python-path }}'
          poetry install --sync --no-root
      - name: Test lower version
        if: ${{ matrix.py-version == '3.8' }}
        run: |
          . $(poetry env info --path)/bin/activate
          pip install numpy==1.18.0 --only-binary :all:
          pip install scipy==1.3.2 --only-binary :all:
          pip install diplib=3.1.0 --only-binary :all:
      - name: Pytest
        run: poetry run pytest
      - name: Build
        run: poetry build
      - name: Upload artifact
        if: ${{ matrix.py-version == '3.10' }}
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ${{ github.workspace }}/dist/
          if-no-files-found: error
  publish:
    needs: [buildtest]
    name: Wheel-Publish
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: ${{ github.workspace }}/dist/
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
    - name: Install wheel test
      run: |
        pip install ${{ github.workspace }}/dist/*.whl
    - name: Publish a Python distribution to PyPI
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
